routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PricesController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserSupportController;
use App\Http\Controllers\CheckController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__.'/auth.php';

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('check', [CheckController::class, 'index'])->name('check.index');
Route::post('check/search', [CheckController::class, 'search'])->name('check.search');

Route::middleware(['auth', 'verified'])->group(function(){

    Route::prefix('account')->group(function(){
        Route::get('/show', []);
    });

    // Orders
    Route::prefix('order')->group(function () {
        Route::get('/', [OrderController::class, 'index'])->name('order.index');
        Route::get('/create', [OrderController::class, 'create'])->name('order.create');
        Route::get('/edit/{id}', [OrderController::class, 'edit'])->name('order.edit');
        Route::post('/store', [OrderController::class, 'store'])->name('order.store');
        Route::post('/update/{id}', [OrderController::class, 'update'])->name('order.update');
        Route::get('/pay/{id}', [OrderController::class, 'pay'])->name('order.pay');
        Route::post('/register', [OrderController::class, 'register'])->name('order.register');
        Route::get('/receipt/{id}', [OrderController::class, 'receipt'])->name('order.receipt');
    });

    // Payments
    Route::prefix('payment')->group(function () {
        Route::get('/create', [PaymentController::class, 'create'])->name('payment.create');
        Route::post('/store', [PaymentController::class, 'store'])->name('payment.store');
        Route::get('/', [PaymentController::class, 'index'])->name('payment.index');
    });

    // Web
    Route::get('prices', [PricesController::class, 'index'])->name('prices.index');
    Route::get('support', [UserSupportController::class, 'index'])->name('support.index');

    Route::prefix('user')->group(function () {
        Route::get('/show/{id}', [UserController::class, 'show'])->name('user.show');
        Route::get('/edit/{id}', [UserController::class, 'edit'])->name('user.edit');
        Route::post('/update/{id}', [UserController::class, 'update'])->name('user.update');
    });

});

Route::get('card', function(){
    return view('generator.template');
});

app/Models/Order.php
<?php


namespace App\Models;


use Aigletter\LaravelAttachment\AttachmentTrait;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use AttachmentTrait;

    protected $casts = [
        'price' => 'float',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'document_issue_date',
        'gas_equipment_next_survey',
        'gas_cylinder_date_last_survey',
        'gas_cylinder_date_next_survey'
    ];

    protected $fillable = [
        "user_id",
        "status",
        "first_name",
        "middle_name",
        "last_name",
        "phone",
        "company",
        "vin",
        "year",
        "brand",
        "model",
        "body",
        "chassis",
        "mileage",
        "power",
        "numberplate",
        "license_category_id",
        "technical_category_id",
        "tires",
        "net_weight",
        "max_weight",
        "fuel_type_id",
        "document_type_id",
        "brake_type_id",
        "price",
        "document_series",
        "document_number",
        "document_issue_date",
        "document_issue_by",
        "tachograph_brand",
        "tachograph_model",
        "tachograph_series",
        "gas_equipment_number",
        "gas_equipment_next_survey",
        "gas_cylinder_serial_number",
        "gas_cylinder_date_last_survey",
        "gas_cylinder_date_next_survey",
        "gas_cylinder_year_issue",
        "car_type"
    ];

    /**
     * Черновик
     */
    public const STATUS_DRAFT = 'draft';

    /**
     * Ожидает оплаты
     */
    public const STATUS_PENDING = 'pending';

    /**
     * Зарегистрирован
     */
    public const STATUS_DONE = 'done';

    /**
     * Удален
     */
    public const STATUS_DELETED = 'deleted';

    public const CAR_TYPE_REGULAR = 'regular';

    public const CAR_TYPE_PASSENGER = 'passenger';

    public const CAR_TYPE_TRUCK = 'truck';

    public const CAR_TYPE_DANGEROUS ='dangerous';

    public const CAR_TYPE_TRAINING ='training';

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function fuelType()
    {
        return $this->belongsTo(FuelType::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function brakeType()
    {
        return $this->belongsTo(BrakeType::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function licenseCategory()
    {
        return $this->belongsTo(LicenseCategory::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function technicalCategory()
    {
        return $this->belongsTo(TechnicalCategory::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function documentType()
    {
        return $this->belongsTo(DocumentType::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function diagnosticCard()
    {
        return $this->hasOne(DiagnosticCard::class);
    }

    /**
     * @return string|null
     */
    public function getStatusNameAttribute()
    {
        return __($this->status);
    }

    /*public function getPdfAttribute()
    {
        return $this->diagnosticCard()->first();
    }*/

    public function outcome()
    {
        return $this->hasOne(Outcome::class);
    }
}

resources/views/check.blade.php
@extends('layouts.main')

@section('content')

    <div class="container block-info block-check">
        <div class="row">
            <div class="col-sm-12 mb_100">
                <h1>Проверка ДК</h1>
            </div>
            <div class="col-sm-12">
                <p>Уважаемые пользователи! Проверка действующей диагностической карты в сервисе единой автоматизированной системы осуществляется путем скоринга данных, введенных в поле формы проверки по базе ЕАИСТО.</p>
                <p style="font-weight: 500;">Необходимо заполнить одно поле формы поиска и нажать кнопку "Проверить"</p>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row mb_30">
            <div class="col-lg-6 table-check">
                <h2>Проверить ДК</h2>
                <form method="post" action="{{ route('check.search') }}">
                    @csrf()
                    <input id="numberplate" name="numberplate" class="form-control" placeholder="Рег. номер А777АА777 - только заглавные русских буквы, цифры и регион">
                    <input id="vin" name="vin" class="form-control" placeholder="Введите VIN номер">
                    <input id="body" name="body" class="form-control" placeholder="Введите номер кузова">
                    <input id="chassis" name="chassis" class="form-control" placeholder="Введите номер шасси">
                    <input id="number" name="number" class="form-control" placeholder="Введите номер ДК  (ЕАИСТО - 15 или 21 знак)">
                    <div class="row">
                        <div class="col-6">
                            <a href="#">R-captcha</a>
                        </div>
                        <div class="form-group col-md-3 col-sm-12 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary btn-lg log-button" id="submit">Проверить</button>
                        </div>
                    </div>

                </form>
            </div>
            <div class="col-lg-6 table-check">
                <h2>Результаты поиска</h2>
                @if(isset($order))
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <td>Регистрационный номер</td>
                            <th scope="row">{{ $order->numberplate }}</th>
                        </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <td>VIN номер</td>
                            <th scope="row">{{ $order->vin }}</th>
                        </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <td>Номер ЕАИСТО</td>
                            <th scope="row">{{ $order->diagnosticCard->number }}</th>
                        </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <td>Марка</td>
                            <th scope="row">{{ $order->brand }}</th>
                        </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <td>Модель</td>
                            <th scope="row">{{ $order->model }}</th>
                        </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <td>Категория</td>
                            <th scope="row">{{ $order->licenseCategory->name }}</th>
                        </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <td>Дата произведения ТО</td>
                            <th scope="row">{{ $order->diagnosticCard->valid_from }}</th>
                        </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <td>Действителен до</td>
                            <th scope="row">{{ $order->diagnosticCard->valid_to }}</th>
                        </tr>
                        </tbody>
                    </table>
                @else
                    <div>
                        Не найдено
                    </div>
                @endif
            </div>
        </div>
    </div>

@endsection

resources/views/index.blade.php
@extends('layouts.main')

@section('content')
    <!--div class="container-fluid block-slide">
        <div class="container main-title">
            <p>Оформляйте техосмотр по<br /> новым правилам</p><span class="">от 01 марта 2021 года</span>
        </div>
        <div class="block-img"></div>
    </div-->


    <div class="wrapper">
        <div class="container">
            <div class="row">

                <div class="col-sm-12 col-md-6 col-lg-4 main-title">
                    <div class="d-flex date-head">
                        <p>Оформляйте техосмотр по<br /> новым правилам</p>
                    </div>
                    <span class="date-head">от 01 марта 2021 года</span>
                    @guest
                        <div class="btn-reg-log">
                            <a href="/register" class="btn btn-light" type="button">Регистрация</a>
                            <a href="/login" class="btn btn-primary-home" type="button">Вход</a>
                        </div>
                    @endguest
                </div>
                <div class="col-sm-12 col-md-6 col-lg-8">
                    <img class="woman-working" src="assets/img/woman-working-office.png">
                </div>
            </div>
        </div>
    </div>

    <div class="container block-home">
        <div class="row mb_100">
            <div class="col-sm-12">
                <h1>Система по оформлению техосмотра<br /> в РФ по новым правилам</h1>
            </div>
        </div>

        <div class="container block_advantage">
            <div class="row">
                <div class="col-sm-12 col-md-3 block_advantage__item">
                    <div class="block_advantage__img_1"></div>
                    <div class="block_advantage__info"><p>Актуальная цена категории "B" 1000 руб.</p></div>
                </div>
                <div class="col-sm-12 col-md-3 block_step__item">
                    <div class="block_advantage__img_2"></div>
                    <div class="block_advantage__info"><p>Способы оплаты пополнение баланса без %</p></div>
                </div>
                <div class="col-sm-12 col-md-3 block_step__item">
                    <div class="block_advantage__img_3"></div>
                    <div class="block_advantage__info"><p>Срок регистрации 10-15 минут</p></div>
                </div>

                <div class="col-sm-12 col-md-3 block_step__item">
                    <div class="block_advantage__img_4"></div>
                    <div class="block_advantage__info"><p>Доступные регионы 75 из 85</p><p><a href="#region_list">Посмотреть список доступных регионов</a></p></div>
                </div>
            </div>
        </div>

    </div>

    <div id="region_list" class="container">

        <table class="table table-bordered table-order-list hide" style="font-weight: 700; font-size: 20px;">
            <thead>
                <tr style="font-weight: 500;">
                    <td>Код</td>
                    <td>Наименование</td>
                    <td>Кол-во доступных станций</td>
                </tr>
                @foreach($regions as $region)
                    <tr>
                        <th>{{ $region->code }}</th>
                        <th>{{ $region->name }}</th>
                        <th>{{ $region->stations->count() }}</th>
                    </tr>
                @endforeach
            </thead>
        </table>

        <table class="table table-bordered table-order-list" style="font-weight: 700; font-size: 20px;">
            <thead>
            <tr style="font-weight: 500;">
                <td>Код</td>
                <td>Наименование</td>
                <td>Кол-во доступных станций</td>
            </tr>

            @foreach($regions->random(7) as $region)
                <tr>
                    <th>{{ $region->code }}</th>
                    <th>{{ $region->name }}</th>
                    <th>{{ $region->stations->count() }}</th>
                </tr>
            @endforeach

            </thead>
        </table>

        <div class="d-flex justify-content-center my-5">
            <button type="button" class="btn btn-primary btn-lg show_region_list">Посмотреть весь список</button>
        </div>

    </div>

@endsection

resources/views/order-list.blade.php
@extends('layouts.main')

@section('content')

    <div class="container block-info">
        <div class="row mb_100">
            <div class="col-md-8 col-sm-12">
                <h1>Список ДК</h1>
            </div>
            <div class="col-md-4 col-sm-12 block-btn">
                <a href="{{ route('order.create') }}" type="button" class="btn btn-primary btn-lg">Создать новую ДК</a>
            </div>
        </div>

        <div class="row">

            <div class="col-sm-12">
                <div class="order-filter">
                    <a href="{{ route('order.index') }}">Все</a>
                    <a href="{{ route('order.index', [
                        'status' => \App\Models\Order::STATUS_DONE
                    ]) }}">Зарегистрирован</a>
                    <a href="">Ожидает регистрации</a>
                    <a href="">Удалена из ЕАИСТО</a>
                    <a href="">Черновик</a>
                </div>

                <table class="table table-bordered table-order-list">
                    <thead>
                    <tr>
                        <th scope="col">Номер</th>
                        <th>Агент</th>
                        <th>Дата и время</th>
                        <th>ТС</th>
                        <th>Статус</th><th>Действие</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($orders as $order)
                        <tr>
                            <td>{{ $order->id }}</td>
                            <td>{{ $user->last_name }}</td>
                            <td>{{ $order->crated_at }}</td>
                            <td>{{ $order->brand }} {{ $order->model }} | {{ $order->numberplate }}
                                {{ $order->licenseCategory->name }}</td>
                            <td>
                                <span class="mark-status-{{ $order->status_name }}">
                                    {{ __(ucfirst($order->status_name)) }}
                                </span>
                                @if($order->status_name === \App\Models\Order::STATUS_DONE)
                                    <br>
                                    № {{ $order->diagnosticCard->number }}
                                @endif
                            </td>
                            <td>
                                @if($order->status == \App\Models\Order::STATUS_DONE)
                                    <a type="button" target="_blank" class="btn btn-primary btn-sm"
                                            href="{{ $order->diagnosticCard->pdf->url }}">
                                        Скачать
                                    </a>
                                @elseif(
                                    $order->status == \App\Models\Order::STATUS_DRAFT
                                    || $order->status == \App\Models\Order::STATUS_PENDING
                                )
                                    <a type="button" class="btn btn-primary btn-sm"
                                            href="{{ route('order.edit', ['id' => $order->id]) }}">
                                        Редактировать
                                    </a>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/order-pay.blade.php
@extends('layouts.main')

@section('content')
    <div class="container block-info">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h1>Личный кабинет агента</h1>
            </div>
            <div class="col-md-4 col-sm-12 block-btn">
                <a href="{{ route('order.create') }}" type="button" class="btn btn-primary btn-lg">Создать новую ДК</a>
            </div>
        </div>
    </div>

    <div class="container block_step">
        <div class="row">
            <x-step step="1" svg="/assets/img/step1.svg" text="Оформление ДК"></x-step>
            <x-step step="2" svg="/assets/img/step2.svg" text="Оплата" :active="true"></x-step>
            <x-step step="3" svg="/assets/img/step3.svg" text="Регистрация и получение"></x-step>
        </div>
    </div>

    <hr>

    <div class="container block-info">

        <div class="row block-receipt">

            <div class="col-md-3 col-sm-12"></div>
            <div class="col-md-6 col-sm-12 table-balance">

                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td>Заказ №</td>
                        <th scope="row">{{ $order->id }}</th>
                    </tr>
                    </tbody>
                </table>

                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td>Категория</td>
                        <th scope="row">{{ $order->licenseCategory->name }} - {{ $order->technicalCategory->name }}
                        </th>
                    </tbody>
                </table>

                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td>Марка и модель ТС</td>
                        <th scope="row">{{ $order->brand }} {{ $order->model }}</th>
                    </tr>
                    </tbody>
                </table>

                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td>Стоимость</td>
                        <th scope="row">{{ $order->price }} руб.</th>
                    </tr>
                    </tbody>
                </table>

                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td>На балансе</td>
                        <th scope="row">{{ auth()->user()->balance }} руб.</th>
                    </tr>
                    </tbody>
                </table>

            </div>

            <div class="row save-button mb_100">
                <div class="col-md-3 col-lg-3 d-none d-sm-none d-md-block"></div>
                <div class="col-sm-12 col-md-3 col-lg-3 block-receipt-btn">
                    <a type="button" href="{{ route('payment.create') }}" class="btn btn-primary btn-lg draft-button">Пополнить баланс</a>
                </div>
                <div class="col-sm-12 col-md-3 col-lg-3 block-receipt-btn">
                    <form method="post" action="{{ route('order.register') }}" id="form" enctype="multipart/form-data">
                        @csrf()
                        <input type="hidden" name="order_id" value="{{ $order->id }}">
                        <button type="submit"
                                class="btn btn-primary btn-lg save-button" {{ $user->balance < $order->price ? 'disabled' : '' }}>
                            Оплатить
                        </button>
                    </form>
                </div>
                <div class="col-md-3 col-lg-3 d-none d-sm-none d-md-block"></div>
            </div>
        </div>

    </div>
@endsection

resources/views/order-receipt.blade.php
@extends('layouts.main')

@section('content')
    <div class="container block-info">
        <div class="container block-info">
            <div class="row">
                <div class="col-md-8 col-sm-12">
                    <h1>Личный кабинет <span class="last-word">агента</span></h1>
                </div>
                <div class="col-md-4 col-sm-12 block-btn">
                    <a href="{{ route('order.create') }}" type="button" class="btn btn-primary btn-lg">Создать новую ДК</a>
                </div>
            </div>
        </div>

        <div class="container block_step">
            <div class="row">
                <x-step step="1" svg="/assets/img/step1.svg" text="Оформление ДК"></x-step>
                <x-step step="2" svg="/assets/img/step2.svg" text="Оплата"></x-step>
                <x-step step="3" svg="/assets/img/step3.svg" text="Регистрация и получение" :active="true"></x-step>
            </div>
        </div>

        <hr class="mb_100">

        <div class="row block-receipt">
            <div class="block-receipt-img">
                <div class="img-ok"></div>
            </div>
            <div class="col-sm-12 text-center">
                <h2>Регистрация ДК прошла успешно!</h2>
            </div>
            <div class="col-sm-12 col-lg-3"></div>
            <div class="col-sm-12 col-lg-6 table-receipt">

                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>Присвоен №</td>
                            <th scope="row">793535733567</th>
                        </tr>
                    </tbody>
                </table>

                <div class="d-lg-none btn-block-check mb_20"><button type="button" class="btn btn-primary btn-lg btn-check">Проверить номер в ЕАИСТО</button></div>

                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>Марка и категория</td>
                            <th scope="row">{{ $order->brand }} {{ $order->model }} - {{ $order->licenseCategory->name }}
                        </th>
                    </tbody>
                </table>

                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td>Гос. регистрационный №</td>
                        <th scope="row">{{ $order->numberplate }}</th>
                    </tr>
                    </tbody>
                </table>

                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td>Лицо, предоставившее ТС</td>
                        <th scope="row">{{ $order->first_name }} {{ $order->last_name }}</th>
                    </tr>
                    </tbody>
                </table>

            </div>
            <div class="d-none d-lg-block col-lg-3  btn-block-check"><button type="button" class="btn btn-primary btn-lg btn-check">Проверить номер в ЕАИСТО</button></div>
        </div>

        <div class="row save-button mb_100">
            <div class="col-sm-12 col-lg-3 d-none d-sm-none d-md-block"></div>
            <div class="col-sm-12 col-lg-3 block-receipt-btn mb_20" style="padding-left: 8px;">
                <button type="button" class="btn btn-primary btn-lg draft-button">Перейти в список ДК</button>
            </div>
            <div class="col-sm-12 col-lg-3 block-receipt-btn" style="padding-left: 8px;">
                <button type="button" class="btn btn-primary btn-lg save-button">
                    <img src="/assets/img/download.png" alt="" style="vertical-align: middle; margin-right: 5px;">
                    Скачать
                </button>
            </div>
            <div class="col-sm-12 col-lg-3 d-none d-sm-none d-md-block"></div>
        </div>

    </div>

@endsection

resources/views/payment-index.blade.php
@extends('layouts.main')

@section('content')
    <div class="container block-info">
        <div class="row mb_100">
            <div class="col-md-8 col-sm-12">
                <h1>История платежей</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <table class="table">
                    <tr>
                        <th>Номер</th>
                        <th>Дата</th>
                        <th>Операция</th>
                        <th>Сумма</th>
                        <th>Остаток</th>
                    </tr>
                    @foreach($payments as $payment)
                        <tr>
                            <td>{{ $payment->id }}</td>
                            <td>{{ $payment->created_at }}</td>
                            <td>
                                @if ($payment->income)
                                    Пополнение счета через {{ $payment->income->paymentMethod->name }}
                                @elseif ($payment->outcome)
                                    Оплата за ДК {{ $payment->outcome->order->brand }}
                                    <br>
                                    {{ $payment->outcome->order->numberplate }} | {{ $payment->outcome->order->last_name }}
                                @endif
                            </td>
                            <td>
                                {{ ($payment->income ? '+' : '') . $payment->amount }}
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>

    </div>
@endsection

resources/views/support-index.blade.php
@extends('layouts.main')

@section('content')

    <div class="container block-info">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h1>Техподдержка</h1>
            </div>
            <div class="col-md-4 col-sm-12">

            </div>
        </div>
    </div>

@endsection