routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PricesController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserSupportController;
use App\Http\Controllers\CheckController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__.'/auth.php';

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('check', [CheckController::class, 'index'])->name('check.index');
Route::post('check/search', [CheckController::class, 'search'])->name('check.search');

Route::middleware(['auth', 'verified'])->group(function(){

    Route::prefix('account')->group(function(){
        Route::get('/show', []);
    });

    // Orders
    Route::prefix('order')->group(function () {
        Route::get('/', [OrderController::class, 'index'])->name('order.index');
        Route::get('/create', [OrderController::class, 'create'])->name('order.create');
        Route::get('/edit/{id}', [OrderController::class, 'edit'])->name('order.edit');
        Route::post('/store', [OrderController::class, 'store'])->name('order.store');
        Route::post('/update/{id}', [OrderController::class, 'update'])->name('order.update');
        Route::get('/pay/{id}', [OrderController::class, 'pay'])->name('order.pay');
        Route::post('/register', [OrderController::class, 'register'])->name('order.register');
        Route::get('/receipt/{id}', [OrderController::class, 'receipt'])->name('order.receipt');
    });

    // Payments
    Route::prefix('payment')->group(function () {
        Route::get('/create', [PaymentController::class, 'create'])->name('payment.create');
        Route::post('/store', [PaymentController::class, 'store'])->name('payment.store');
        Route::get('/', [PaymentController::class, 'index'])->name('payment.index');
    });

    // Web
    Route::get('prices', [PricesController::class, 'index'])->name('prices.index');
    Route::get('support', [UserSupportController::class, 'index'])->name('support.index');

    Route::prefix('user')->group(function () {
        Route::get('/show/{id}', [UserController::class, 'show'])->name('user.show');
        Route::get('/edit/{id}', [UserController::class, 'edit'])->name('user.edit');
        Route::post('/update/{id}', [UserController::class, 'update'])->name('user.update');
    });

});

Route::get('card', function(){
    return view('generator.template');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable;

    public const STATUS_REGISTERED = 1;
    public const STATUS_VERIFIED = 2;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'first_name',
        'last_name',
        'middle_name',
        'region_id',
        'city',
        'need',
        'insurance_company',
        'phone',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected function getStatuses()
    {
        return [
            'registered' => self::STATUS_REGISTERED,
            'verified' => self::STATUS_VERIFIED,
        ];
    }

    public function changeStatus(int $status)
    {
        if (!in_array($status, $this->getStatuses())) {
            throw new \Exception('Unknown status');
        }

        $this->status = $status;
        $this->save();
    }

    public function getStatus()
    {
        $statuses = $this->getStatuses();
        foreach ($statuses as $key => $value) {
            if ($this->status === $value) {
                return $key;
            }
        }

        return null;
    }

    public function region()
    {
        return $this->belongsTo(Region::class);
    }

    public function payments()
    {
        return $this->hasMany(Payment::class)->where('status', 1);
    }

    public function getBalanceAttribute()
    {
        return (float) $this->payments()->sum('amount');
    }
}

resources/views/partials/logo.blade.php
<a class="navbar-brand" href="/">
    <img src="/assets/img/logo4-2.jpg" class="logo">
</a>

resources/views/partials/nav-guest.blade.php
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
        @include('partials.logo')
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample07">
            <div class="navbar-block-menu flex-grow-1">
                <ul class="navbar-nav justify-content-end">

                    <li class="nav-item">
                        <a class="nav-link" href="/check">Проверка ДК</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">О сервисе</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-block-lk">
                <a href="{{ route('login') }}" class="btn btn-primary btn-lg">Вход/Регистрация</a>
            </div>
        </div>
    </div>
</nav

resources/views/partials/nav-user.blade.php
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
        @include('partials.logo')
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07"
                aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample07">
            <div class="navbar-block-menu flex-grow-1">
                <ul class="navbar-nav justify-content-end">

                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('order.create') }}">Создать ДК</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('order.index') }}">Список ДК</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/check">Проверка ДК</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('prices.index') }}">Цены</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('payment.create') }}">Балланс - {{ auth()->user()->balance }} руб.</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('support.index') }}">Техподдержка</a>
                    </li>

                </ul>
            </div>
            <div class="navbar-block-lk flex-grow-1">
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Привет, {{ auth()->user()->first_name }}</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown07">
                            <a class="dropdown-item" href="#">ID: {{ auth()->id() }}</a>
                            <a class="dropdown-item" href="#">Статус: {{ auth()->user()->getStatus() }}</a>
                            <a class="dropdown-item" href="{{ route('payment.index') }}">История платежей</a>
                            <a class="dropdown-item" href="{{ route('user.show', ['id' => auth()->id()]) }}">Настройки аккаунта</a>
                            <a class="dropdown-item" href="{{ route('logout') }}">Выйти</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>